name: Test setup-node caching
on: [push, workflow_dispatch]
jobs:
  run:
    name: Node test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ macos-11 ]
        version: [ '14.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: npm install -g yarn@2
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
        cache: yarn
        
#     - uses: actions/cache@v2
#       name: Yarn cache
#       timeout-minutes: 2
#       with:
#         path: '**/node_modules'
#         key: macos11-yarn-${{ hashFiles('**/yarn.lock') }}
#         restore-keys: |
#           macos11-yarn-
    - name: Node version
      shell: pwsh
      run: node --version
    - name: Yarn version
      run: yarn --version
    - run: yarn install
      timeout-minutes: 7
